### ISSUE TITLE
Small number suppression malfunctioning in measures

### ISSUE THREAD

**Issue by robinyjpark** [opensafely-core/cohort-extractor#626] opened 2021-07-29 11:39 UTC
I generated measures counting abnormal test results by month and sex with `small_number_suppression=True`. The resulting output by female had missing values (only 5 of 30 months were populated), though the data by male were complete. 

When re-running the measures without the `small_number_suppression` argument, the data are properly populated, and the lowest number is >10,000. 

Strangely, when I run the measures with a more limited population (patients with type 2 diabetes only) while still suppressing small numbers, there are no missing values in the resulting output. 

@benbc @alexwalkercebm

**Comment by benbc** [comment] 2021-08-17 14:23
Hello, @robinyjpark. Could you point me at a study definition where you've tried to do this? As far as I know you're the first person to try this out, so I'd really like to look into it and fix the problem.

**Comment by alexwalkercebm** [comment] 2021-08-17 14:46
It's [this one](https://github.com/opensafely/HbA1c-levels/blob/7362e585795b4d5741af2557e635f49f53ef8e04/analysis/study_definition.py).

If I remember rightly, things were fine in the dummy data, and the problem only emerged in real data, and even then only in one of the measures (where the suppression option is commented out).

**Comment by robinyjpark** [comment] 2021-08-17 15:38
Yes, as Alex said, fine on the dummy data but not on the real data. I commented out the suppression option for all analyses by sex, but `id = t2dm_hba1c_abnormal_by_sex` (smaller subset) looked as expected while `id = hba1c_abnormal_by_sex` did not (resulted in missing data points).

**Comment by benbc** [comment] 2021-08-17 15:49
Thank you.

I think I've understood that there weren't actually _any_ small numbers in the measure where suppression was happening -- is that right?

**Comment by benbc** [comment] 2021-08-17 15:58
Are there other measures where there _is_ legitimate suppression going on?

**Comment by robinyjpark** [comment] 2021-08-17 16:12
I don't believe so – the counts are high enough that nothing should be suppressed.

**Comment by benbc** [comment] 2021-08-17 16:24
Well that's Theory One out of the window then. :-)

**Comment by StevenMaude** [comment] 2021-11-29 11:34
There's another report of what is possibly this issue in the [Q&A forum](https://github.com/opensafely/documentation/discussions/488#discussioncomment-1714827).

**Comment by benbc** [comment] 2023-01-12 11:51
We haven't had any more reports of this problem and I couldn't reproduce it, so I'm going to close it and we can reconsider if it comes up again.

**Closed by benbc** 2023-01-12 11:51 UTC
