### ISSUE TITLE
Provide unified way of querying for immunisations

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#464] opened 2021-02-12 13:00 UTC
For an vaccine event, we might want to know the vaccine's target disease (eg covid), as well as what particular product was used (eg AZ, Pfizer, etc).

In TPP, we have a single table `Vaccination` which has rows indicating both the target disease and the product.  We can query this via `with_tpp_vaccination_record(target_disease_matches=..., product_name_matches=...)`.  Both fields contain strings.

In EMIS, we have data in two tables containing vaccine data:

* `immunisation_all_orgs_v2` contains records indicating that a vaccine targetting a disease has been administered (eg [Administration of first dose of severe acute respiratory syndrome coronavirus 2 vaccine (procedure)](https://codelists.opensafely.org/snomedct/concept/1324681000000101/)).  Records contain SNOMED codes.
* `medication_all_orgs_v2` contains records indicating why product has been administered (eg [COVID-19 mRNA Vaccine BNT162b2 30micrograms/0.3ml dose concentrate  for suspension for injection multidose vials (Pfizer-BioNTech) (Pfizer  Ltd)](https://openprescribing.net/dmd/amp/39115611000001103/)).  Records contain dm+d codes.

There is not a perfect correspondence between records in `immunisation_all_orgs_v2` and `medication_all_orgs_v2`.  For instance, at one point ~6% of patients with a recorded first dose of a covid vaccine did not have a corresponding record in `medication_all_orgs_v2`, and ~2% of patients with a recorded Pfizer dose in `medication_all_orgs_v2` had no corresponding record in `immunisation_all_orgs_v2`.

We'd like to provide a unified way of querying for immunisations.

My proposal is to update the `with_tpp_vaccination_record` variable to support something like:

```
patients.with_vaccination_record(
  tpp={"target_disease_matches": ..., "product_name_matches": ...},
  emis={target_disease_codes": ..., "product_codes": ...},
  ...
)
```

This would allow us to support everything that's currently supported in TPP, and to support something similar in EMIS, with a single study definition.

We could add an optional `operator` parameter that determines how the `target_disease_xxx` and `product_xxx` fields are combined.  It would default to `"and"` (which `with_tpp_vaccination_record` already does) but if it were `"or"`, it would allow us to find the 2% of patients with a recorded Pfizer dose in `medication_all_orgs_v2` had no corresponding record in `immunisation_all_orgs_v2`.  I'm not sure whether this is worth it.

**Comment by sebbacon** [comment] 2021-02-12 15:37
I've [asked in Slack](https://ebmdatalab.slack.com/archives/C010SJ89SA3/p1613144154334500) if TPP could provide codes rather than name-strings in the `Vaccination` table, as this would make our API much cleaner!

An alternative, as long as we're just dealing with C19 vaccinations, would be to code this subset manually ourselves, though we'd then probably want a separate `patients.with_covid19_vaccination_record` to make this explicit.

**Comment by inglesp** [comment] 2021-02-15 13:41
OK, so what about:

```
patients.with_vaccination_record(
  target_disease_codes=[...],
  vaccination_product_codes=[...],
  ...
)
```

For TPP, we'd maintain a lookup between SNOMED codes and the names of target diseases and products, and we'd pass these names into `.with_tpp_vaccination_record`.  We'd hope that eventually TPP would expose SNOMED codes, but if this isn't possible, `.with_tpp_vaccination_record` can stay around.

For EMIS, if just `target_disease_codes` was provided, we'd query `immunisation_all_orgs_v2` and if just `vaccination_product_codes`, we'd query `medication_all_orgs_v2`.  If both were provided, we'd query both tables and return patients with records in both.  This matches the behaviour of TPP, and if a researcher wanted to find patients with records in either table, they could do so by providing two separate queries.

**Comment by evansd** [comment] 2021-02-15 13:56
@inglesp I think this sounds sensible

**Comment by sebbacon** [comment] 2021-02-15 14:06
Looks good, but one leftfield thought to add:

If we're saying people who want to `OR` the codelists need to make two separate variables, this then makes me wonder if we can actually go a step further and just fold this all into `with_these_clinical_events` and `with_these_medications`?

The TPP implementation would sniff for known-mapped codes and do the right thing in the background?

If we go with your proposal, then I think the following needs to be clear:
> sometimes we only have a record that (say) a covid vaccination was given, but we don't know what product was given

**Comment by inglesp** [comment] 2021-02-15 14:09
> If we're saying people who want to `OR` the codelists need to make two separate variables, this then makes me wonder if we can actually go a step further and just fold this all into `with_these_clinical_events` and `with_these_medications`?

Would that mean querying `immunisation_all_orgs_v2` for every single `with_these_medications` query?

**Comment by sebbacon** [comment] 2021-02-15 14:13
> Would that mean querying immunisation_all_orgs_v2 for every single with_these_medications query?

I suppose it would - not necessarily a big problem though - I mean, it *might* be, we'd not know til we tried (I suppose we'd `UNION ALL` before querying?)

**Comment by inglesp** [comment] 2021-02-15 14:14
> I suppose we'd `UNION ALL` before querying?

Yes, something like that.

As we don't need this now, maybe wait until it's all in SQLite?

**Comment by HelenCEBM** [comment] 2021-03-09 15:26
Duplicate of #422 ? And also completed @inglesp ?

**Closed** 2021-03-09 16:04 UTC
